# Generated by Django 4.2.2 on 2023-07-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='warehouse_item',
        ),
    ]
